[env]
# OpenCV 环境变量
OPENCV_DIR = "C:\\opencv\\build"
OPENCV_INCLUDE_PATHS = "C:\\opencv\\build\\include"
OPENCV_LINK_PATHS = "C:\\opencv\\build\\x64\\vc16\\lib"
OPENCV_LINK_LIBS = "opencv_world4120"
# LLVM for bindgen
LIBCLANG_PATH = "C:\\LLVM\\bin"
